package utils.exception;
/**
 * This exception happens when anonymous errors happens during test exercises
 */
public class TestUnknownFailureException extends Exception{
}
